### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by tomasalias** [Av32000/GarticCheat#2]
What is this lil bro?

![image](https://github.com/user-attachments/assets/0223ed89-5e1c-4b2e-b90b-770db781bb09)

**Comment by Av32000** [comment]
I think it's because it listens to the user's inputs to get the position of the image. There also appears to be an error in the published build. It was a Debug version and not a Realease version that was on Github. I've just corrected it
![image](https://github.com/user-attachments/assets/62b487c1-7c2b-4e4e-9dfa-95081d7f3c50)
New Scan with the Release Build :
![image](https://github.com/user-attachments/assets/fd6a44c5-70a0-4281-93b0-9df93eb35b46)

**Comment by jadebi** [comment]
Are you sure this is not a virus??

**Comment by Av32000** [comment]
Yes sure.

If you don't trust me (understandable) you can read the code and build it from scratch.

**Comment by coffandro** [comment]
> What is this lil bro?
> 
> ![image](https://private-user-images.githubusercontent.com/80042910/357934097-0223ed89-5e1c-4b2e-b90b-770db781bb09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzAyNzAsIm5iZiI6MTcyOTc2OTk3MCwicGF0aCI6Ii84MDA0MjkxMC8zNTc5MzQwOTctMDIyM2VkODktNWUxYy00YjJlLWI5MGItNzcwZGI3ODFiYjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDExMzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMDhjODdiMThiNzU2NzlkMzllZWY0OWNkNDExYzc5N2U4YjhiNTI4Njg5YWQ2ZWNmZWFlY2M1YWM3NDdiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.enQgwv8f1cThc5-TZtc__t1lmKU-CWbdRkuny4uQGqw)

Virustotal is *very* prone to false positives
